#======================================#
#========== Server settings ===========#
#======================================#
server:
  port: 5555
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

spring:
  main:
    allow-bean-definition-overriding: true
  # application name
  application:
    name: traffic.cloud.engie

  # current environment config
  profiles:
    active: default

  # jdbc datasource config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://api.ruiwuo.com:3306/traffic_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Laymat@123
    testSql: SELECT 1

  freemarker:
    # 这个是配置模板路径的，默认是templates
    template-loader-path: classpath:/templates
    suffix: .ftl
    encoding: UTF-8
    # 这个开发配置为false，避免改了模板还要重启服务器
    cache: false
    enabled: true

  # enabled hot load
  devtools:
    livereload:
      enabled: true
      port: 5556

  # Redis connector config (RedisProperties)
  redis:
    host: api.ruiwuo.com
    port: 6379
    ssl: false
    database: 3
    password: laymat@123
    timeout: 2000

  # mybatis config
  mybatis:
    configuration:
      map-underscore-to-camel-case: false
      default-fetch-size: 100
      default-statement-timeout: 30
      logImpl: org.apache.ibatis.logging.stdout.StdOutImpl

  # spring mvc config
  mvc:
    view:
      prefix: /static/
      suffix: .html
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB