spring:
  # jdbc datasource config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/trade_market?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: trade
    password: Haoge@123456
    testSql: SELECT 1

  # Redis connector config (RedisProperties)
  redis:
    host: 127.0.0.1
    port: 6379
    ssl: false
    database: 3
    password: laymat@123
    timeout: 2000
